name: Deploy
on:
  push:
    branches:
      - main
    tags: 
      - "v*"
  pull_request: 
    branches-ignore: [ main ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test: 
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt ++ test 

publish:
  needs: test
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Release
      run: 
      - name: Release
      run: sbt ci-release
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        PGP_SECRET: ${{ secrets.PGP_SECRET }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
    
    
